In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0])

[1 2 3 4]


In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
arr = np.array([1,2,3,4,5,6,7,8])

In [12]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [14]:
np.delete(arr,7)

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
np. sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a.ndim

2

In [17]:
a.size

12

In [18]:
a.shape

(3, 4)

In [20]:
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr[np.newaxis]

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [26]:
row_vector = arr[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 8)
[[1 2 3 4 5 6 7 8]]


In [28]:
col_vector = arr[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(8, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [32]:
data = np.array([1,2,3,4,5])
print(data)
print(data[0])
print(data[-1])
print(data[1:2])

[1 2 3 4 5]
1
5
[2]


In [35]:
print(a[a>=7])
print(a[a%2==0])

[ 7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [46]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print("V-Stack\n", np.vstack((arr1,arr2)))
print("H-Stack\n", np.hstack((arr1,arr2)))

V-Stack
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
H-Stack
 [[1 2 5 6]
 [3 4 7 8]]


In [48]:
np.hsplit(arr1,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [51]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr1 - arr2

array([[-4, -4],
       [-4, -4]])

In [55]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [56]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [57]:
arr1 / arr2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [58]:
arr.sum()

36

In [60]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [61]:
arr.min()

1

In [62]:
arr.max()

8

In [63]:
arr.std()

2.29128784747792

In [81]:
np.random.random((3,2))

array([[0.36853073, 0.95364742],
       [0.58005582, 0.19640981],
       [0.51938834, 0.98472005]])

In [83]:
arr1.T

array([[1, 3],
       [2, 4]])

In [84]:
import matplotlib as plt